[gcp_service_account]
type = "service_account"
project_id = "anubankys-hr-system"
private_key_id = "197da55ab2325302797fdf66beb6ab783cc1bab6"

# ใช้ triple quotes เพื่อเก็บคีย์แบบหลายบรรทัด ป้องกัน error "No key could be detected"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCXXAvs72dZ9Pg2
VQbn3lxmOO/FfPvlhKGh5SIiJI09/tSfjG1owjyafYIQavI3Ms+7dFAbMTckeKAv
3cThK+xJwg0hWRrQibP2lM278l2aZV7WFy1Y+632/Cu8WdDVRgrgOqskxppjDoWC
2eBxcgh5mlwChNUtIGbG8KU+QTLJ/VSZ4wpniAnN90VhWOOPz1vcDAAngMEYrOWZ
AcvQCf6wl4O/c/mIIGyrOql2s0aaedW0yvvlBWm5bQsycYh88qMwQu9Rxu1jRKJx
8xJU0AublmgRt3K68QiNIeO+e4Wpn1+2OWo3mb9tUoP8fTH7Xut2EFwOzVPWUH10
VH7eFjnPAgMBAAECggEARN9Yedax44gJjceA3e8bglQ0Hlvxzw1b8uvtbTXOo0Aa
hgMDIeEIbI/hqBDR6HYRek3Bya3KVqkg0scJuCAhY6qOCPefsPaH0hMBzpzJJOEt
lyNyugPDtBgo2orP8MvvVPq9N327cImCDPmRHG30F0k6xtakneUZfzqvJjXKo4gU
NefzJlYrEgCcAzOEC2DVbFJXugac5oqp9wqTUK1F4SU0pS/ZMmXFVmRd3itx9gP0
UVDJw6xXzjFYcEXk4ildCoNHdtz49DjJF03N2EhoSYYc9X5KvpNJi1I7SrQZjxcF
hdtYVag4N4Lzjn+ibAA6F9nn46UlDjiN5HgeEg5O+QKBgQDM/k/0WxUTNxiCEYDZ
UtWbSlqCo5EZLtcw5aWnsouIOsb+BQbd9qloF8WJts+6xW/mkos5UKkHNRS2RJdz
H5xrpcI2gNi8l4TaHsKgCOOxbHIquHMt/Lie7mRGtJpZ0GbZ9YF2bRsAcAR0hRR0
tit0YQPzZPySckyYViNEbfrw3QKBgQC9BVxTJHdHHGoMFbRrqkrX+CKDnacOlVc7
3fF5lLPhMDo3mvw+RgHH6FXmVw00uINXtWD7SzGcyvxtveMavyN0akhAwFdg9B2v
r7+yFnB2s99ckvhLDcggJfMHpGO9d3jZkJpv3RE75aT6e1+hvibe7czGFZXtlLFn
sFXuYse0mwKBgA/OJ+ICR8y0ecpFiTa4YUnY4MOj0uMrLmJRwoT8ii+VwJQDVTU1
+HfTJWLp2nhfErKnZ96ibnXkzNUE0tyIemn+XMwRASUBVbfvmTf3l36titvqXs8T
5jQy0z50XFZCcDur5zB3VxagjGdjf2FETnNpq4FPrv2nnGo+cfertyZtAoGAA9YC
A6Xvzb+j307pdG3mSu+8M5OVelRJiut8JQ2BgQZriAlbKSBelOIALEaD/BfqgnMp
3q+t+BKegNOjsj1CyPAHO1kr7MnHeHNGnqSZ767Cz6wj4dILx6s9fWA2rfeoujGX
EMIZwW9to6+xRyUGwOtuhm6VtlaYKxSHCelzSBUCgYBKpOBiTJLlXbolk984OjM4
mjfQmbcofciiWhK7cISKEmMmK1DicIFEuP1QGbaAhFYzywI1CxWh6EcwW5YBAJGU
QEz6FkSt3tp30E14H16V+wlfeuPXNCNWxSZrdgRylgjFTOTphNZ3UU9uEH3SQZuE
ju2Si4jaoZCtKE6cRKFgyg==
-----END PRIVATE KEY-----
"""

client_email = "anubankys-hr-service@anubankys-hr-system.iam.gserviceaccount.com"
client_id = "107416237611138605128"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/anubankys-hr-service%40anubankys-hr-system.iam.gserviceaccount.com"

[gsheets]
# แก้ไขเป็น Sheet ID ของไฟล์ Users ของครู (ถ้า ID นี้ไม่ใช่ของจริงของครู ให้เปลี่ยน)
users_sheet_id = "1_jJStc8z4C4AoCAYqyPIqgTufgfqJwQdsiu7GnTzkUY"
users_worksheet = "users"
