[gcp_service_account]
type = "service_account"
project_id = "YOUR_PROJECT_ID"
private_key_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
private_key = """-----BEGIN PRIVATE KEY-----
<คีย์หลายบรรทัดจากไฟล์ JSON วางตรงนี้แบบเดิมทุกบรรทัด>
-----END PRIVATE KEY-----
"""
client_email = "xxxx@xxxx.iam.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/xxxx.iam.gserviceaccount.com"

[gsheets]
users_sheet_id   = "YOUR_SHEET_ID"
users_worksheet  = "users"
